server:
  port: 8600
spring:
  mvc:
    favicon:
      enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
# sso
edpglobal:
  sso:
    enabled: false
  fs:
    current: local
    permit-apps: edpglobal-auth
    default-image: classpath:/default.jpg
    hdfs:
      uri: hdfs://10.32.15.84:8020
      workspace: /user/hdfs/edpglobal/fs
    local:
      workspace: /edpglobal/fs
# eureka
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://datahub.eureka.node1.com:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 3