server:
  port: 8081
spring:
  application:
    name: http-fs-demo
  main:
    banner-mode: 'off'
# thymeleaf
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enable-spring-el-compiler: false
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    reactive:
      max-chunk-size: 0
    servlet:
      content-type: text/html
    suffix: .html
# logging
logging:
  file: logs/${spring.application.name}.log
  file.max-size: 100MB
  level:
    root: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    level: '%5p'